---
title: "populationdynamics"
author: "Amelia Harvey"
date: "3/4/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

we want to simulate basic poplation dynamics process
$$x_{t+1}=X_t+r X_t \left(1 - \frac{x_t}{K} \right)$$
```{r}
x0<-10
r<-1
K<-100
tmax<-100
```

```{r}
f<-function(x,r=1,K=100){x+r*x*(1-x/K)}

f(20,)
```

```{r}
tmax<-100
df<- tibble(x=x0, t=0)


for(t in 1:tmax){
  #df%>%select(x%>%filter(t==t))
  x_t<-df[t, "x"][[1]]
  x_tl<-f(x_t, r=2, K=100)

  df<-bind_rows(df,
                tibble(x=x_tl, t=t))}

df%>%ggplot(aes(t, x))+geom_line()
```

```{r}

#df%>%filter(t>80)

r_output<-function(r){for(t in 1:tmax){
  x_t<-df[t, "x"][[1]]
  x_tl<-f(x_t,r=r)

  df<-bind_rows(df,
                tibble(x=x_tl, t=t))}}



r_output(2)

df%>%ggplot(aes(t, x))+geom_line()



```
```{r}
r_values<-seq(1,3,length.out=100)
r_results<-tibble(x=x0, t=0, r=1)
for(r in r_values){
 r<2.1
  tmp<-r_output(r)
  tmp$r_value<-r
 r_results<- bind_rows(r_results,
tmp)
}

```












